// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzJY4upaprJZLevSr6NEtkqIw0sRaItg',
    appId: '1:508761016767:web:e5607ab432818feb2af90a',
    messagingSenderId: '508761016767',
    projectId: 'messanger-app-8651c',
    authDomain: 'messanger-app-8651c.firebaseapp.com',
    storageBucket: 'messanger-app-8651c.firebasestorage.app',
    measurementId: 'G-M95M6Y8JK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Eo3uJW3jWNcIZuuETVDMRfLrRKUCsLM',
    appId: '1:508761016767:android:0e38fdbe52c33f7c2af90a',
    messagingSenderId: '508761016767',
    projectId: 'messanger-app-8651c',
    storageBucket: 'messanger-app-8651c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ZXinwXa4ZfUvTIrZe4jl5VfhjXeoKs8',
    appId: '1:508761016767:ios:98a6380e1f5efba92af90a',
    messagingSenderId: '508761016767',
    projectId: 'messanger-app-8651c',
    storageBucket: 'messanger-app-8651c.firebasestorage.app',
    iosBundleId: 'com.example.realtimeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ZXinwXa4ZfUvTIrZe4jl5VfhjXeoKs8',
    appId: '1:508761016767:ios:98a6380e1f5efba92af90a',
    messagingSenderId: '508761016767',
    projectId: 'messanger-app-8651c',
    storageBucket: 'messanger-app-8651c.firebasestorage.app',
    iosBundleId: 'com.example.realtimeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpzJY4upaprJZLevSr6NEtkqIw0sRaItg',
    appId: '1:508761016767:web:cbd0fe85be98c2142af90a',
    messagingSenderId: '508761016767',
    projectId: 'messanger-app-8651c',
    authDomain: 'messanger-app-8651c.firebaseapp.com',
    storageBucket: 'messanger-app-8651c.firebasestorage.app',
    measurementId: 'G-HM9C1JWR4L',
  );
}
